services:
  nginx:
    image: nginx:1.27-alpine
    container_name: opslab-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - opslab-network

  backend:
    build:
      context: ./backend
    container_name: opslab-backend
    environment:
      PORT: 3000
      DATABASE_URL: postgres://opslab:opslab_password@postgres:5432/opslab_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - opslab-network

  postgres:
    image: postgres:16-alpine
    container_name: opslab-postgres
    environment:
      POSTGRES_USER: opslab
      POSTGRES_PASSWORD: opslab_password
      POSTGRES_DB: opslab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opslab-network

  redis:
    image: redis:7-alpine
    container_name: opslab-redis
    networks:
      - opslab-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: opslab-cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - opslab-network

  prometheus:
    image: prom/prometheus:latest
    container_name: opslab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - opslab-network

  grafana:
    image: grafana/grafana:latest
    container_name: opslab-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - opslab-network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
  
networks:
  opslab-network:
    driver: bridge
